version: '1.0'
services:
  gateway_service:
    image: gateway
    ports:
      - "3000:3000"
    networks:
      - new-hncst

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: turbo_turbo
    ports:
      - "3306:3306"
    networks:
      - new-hncst

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - new-hncst

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    networks:
      - new-hncst

networks:
  new-hncst:
