export * from './division.controller'
export * from './employee.controller'
export * from './file.controller'
export * from './student.controller'
export * from './type.controller'
export * from './admin.controller'